export const GET_USER_INFO = 'GET_USER_INFO';
export const PROFILE_FETCH_ERROR = 'PROFILE_FETCH_ERROR';
export const SET_PROFILE_IMAGE = 'SET_PROFILE_IMAGE';
export const SET_PROFILE_IMAGE_ERROR = 'SET_PROFILE_IMAGE_ERROR';
export const SET_EMAIL_NOTIFICATION = 'SET_EMAIL_NOTIFICATION';
export const SET_EMAIL_NOTIFICATION_ERROR = 'SET_EMAIL_NOTIFICATION_ERROR';
