export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_INVALID_INPUTS = 'LOGIN_INVALID_INPUTS';
export const LOGIN_VALID_INPUTS = 'LOGIN_VALID_INPUTS';
